# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0fae77360d4512ca9a432885214c3541140875a8c78ba093b21307f9f8b6573619671cb8332387f97401ad89bd84579ed18a19006a2816b958adeb6f436aed81

test:
  secret_key_base: 9ee76c00b7b6aec54c78be6e3af3cbd67cb937f120f72054c1afd34a97c2c7c699a6e0bc6c046668a2e1993e5ab384744e77a8947b896727377c1b79dbd745bb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
